services:
  server:
    build: ./server
    container_name: smart_mirror_server
    restart: unless-stopped

    ports:
      - "5000:5000"

    environment:
      PORT: 5000
      SKIN_ANALYSIS_SERVICE_URL: skin-analysis-service:50053
      FACE_RECOGNITION_SERVICE_URL: face-recognition-service:50054
      WHISPER_SERVICE_URL: whisper-service:50051

    networks:
      - backend

    depends_on:
      - whisper-service
      - skin-analysis-service
      - face-recognition-service

  nginx:
    build:
      context: .
      dockerfile: ./infra/nginx/Dockerfile
      args:
        VITE_SPEEinternalCH_THRESHOLD: 60
        VITE_END_OF_SPEECH_MS: 1200
        VITE_MIN_RECORDING_MS: 1200
        VITE_SKIN_OVERLAY_DURATION: 5000

    container_name: smart_mirror_nginx
    restart: unless-stopped

    ports:
      - "443:443"

    networks:
      - public
      - backend

    depends_on:
      - server

  whisper-service:
    build:
      context: ./services/whisper-service
    container_name: whisper-service
    restart: unless-stopped

    ports:
      - "50051:50051"

    networks:
      - backend



  skin-analysis-service:
    build:
      context: ./services/skin-analysis-service
    container_name: skin-analysis-service
    restart: unless-stopped

    environment:
      MODEL_CONFIDENCE: 0.1
      DEFAULT_IOU: 0.7

    ports:
      - "50053:50053"

    networks:
      - backend


  face-recognition-service:
    build:
      context: ./services/face-recognition-service
    container_name: face-recognition-service
    restart: unless-stopped

    ports:
      - "50054:50054"

    networks:
      - backend

  # mkcert:
  #   build:
  #     context: ./infra/mkcert
  #   volumes:
  #     - .:/app
  #   working_dir: /app

networks:
  public:
    driver: bridge

  backend:
    driver: bridge
