services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: smart_mirror_server
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      CLIENT_ORIGIN: http://localhost:5173
      WHISPER_URL: http://whisper-service:8000/transcribe
      SKIN_ANALYSIS_URL: http://skin-analysis-service:8000
    ports:
      - "3000:3000"
  client:
    build:
      context: ./client
    container_name: smart_mirror_client
    ports:
      - '5173:5173'
    restart: unless-stopped
  whisper-service:
    build:
      context: ./services/whisper-service
    container_name: whisper-service
    ports:
      - '8000:8000'
    restart: unless-stopped
  skin-analysis-service:
    build:
      context: ./services/skin-analysis-service
    container_name: skin-analysis-service
    ports:
      - '8001:8000'
    restart: unless-stopped
  audio-processing-service:
    build:
      context: ./audio-processing-service
    container_name: audio-processing-service
    ports:
      - '8002:8000'
    restart: unless-stopped