services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart_mirror_server
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://root:root@mongo:27017/mirror?authSource=admin
      CLIENT_ORIGIN: http://localhost:5173
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
  whisper:
    build:
      context: ./whisper
    container_name: faster-whisper
    volumes:
      - ./audio:/audio