# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio_processor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'audio_processor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61udio_processor.proto\x12\x05voice\"r\n\x12\x41udioStreamRequest\x12\x0b\n\x03pcm\x18\x01 \x01(\x0c\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x04 \x01(\x05\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x03\"\x81\x02\n\x18\x41udioStreamEventResponse\x12.\n\x0espeech_started\x18\x01 \x01(\x0b\x32\x14.voice.SpeechStartedH\x00\x12*\n\x0cspeech_frame\x18\x02 \x01(\x0b\x32\x12.voice.SpeechFrameH\x00\x12*\n\x0cspeech_ended\x18\x03 \x01(\x0b\x32\x12.voice.SpeechEndedH\x00\x12\x30\n\x0futterance_ready\x18\x04 \x01(\x0b\x32\x15.voice.UtteranceReadyH\x00\x12\"\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x11.voice.ErrorEventH\x00\x42\x07\n\x05\x65vent\"%\n\rSpeechStarted\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x03\"\x83\x01\n\x0bSpeechFrame\x12\x13\n\x0b\x63leaned_pcm\x18\x01 \x01(\x0c\x12\x1a\n\x12speech_probability\x18\x02 \x01(\x02\x12\x14\n\x0cspeech_ratio\x18\x03 \x01(\x02\x12\x17\n\x0f\x63ontains_speech\x18\x04 \x01(\x08\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x03\"T\n\x0bSpeechEnded\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x03\x12\x1a\n\x12\x66inal_speech_ratio\x18\x02 \x01(\x02\x12\x13\n\x0b\x64uration_ms\x18\x03 \x01(\x05\"q\n\x0eUtteranceReady\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0b\n\x03pcm\x18\x02 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x05\x12\x13\n\x0b\x64uration_ms\x18\x04 \x01(\x05\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x03\"+\n\nErrorEvent\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2f\n\x0e\x41udioProcessor\x12T\n\x12ProcessAudioStream\x12\x19.voice.AudioStreamRequest\x1a\x1f.voice.AudioStreamEventResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_processor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOSTREAMREQUEST']._serialized_start=32
  _globals['_AUDIOSTREAMREQUEST']._serialized_end=146
  _globals['_AUDIOSTREAMEVENTRESPONSE']._serialized_start=149
  _globals['_AUDIOSTREAMEVENTRESPONSE']._serialized_end=406
  _globals['_SPEECHSTARTED']._serialized_start=408
  _globals['_SPEECHSTARTED']._serialized_end=445
  _globals['_SPEECHFRAME']._serialized_start=448
  _globals['_SPEECHFRAME']._serialized_end=579
  _globals['_SPEECHENDED']._serialized_start=581
  _globals['_SPEECHENDED']._serialized_end=665
  _globals['_UTTERANCEREADY']._serialized_start=667
  _globals['_UTTERANCEREADY']._serialized_end=780
  _globals['_ERROREVENT']._serialized_start=782
  _globals['_ERROREVENT']._serialized_end=825
  _globals['_AUDIOPROCESSOR']._serialized_start=827
  _globals['_AUDIOPROCESSOR']._serialized_end=929
# @@protoc_insertion_point(module_scope)
