# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: face_recognition.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'face_recognition.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x66\x61\x63\x65_recognition.proto\x12\x0bvision.face\"!\n\x10RecognizeRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"A\n\x11RecognizeResponse\x12,\n\x0bpredictions\x18\x01 \x03(\x0b\x32\x17.vision.face.Prediction\".\n\nPrediction\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x32]\n\x0f\x46\x61\x63\x65Recognition\x12J\n\tRecognize\x12\x1d.vision.face.RecognizeRequest\x1a\x1e.vision.face.RecognizeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'face_recognition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOGNIZEREQUEST']._serialized_start=39
  _globals['_RECOGNIZEREQUEST']._serialized_end=72
  _globals['_RECOGNIZERESPONSE']._serialized_start=74
  _globals['_RECOGNIZERESPONSE']._serialized_end=139
  _globals['_PREDICTION']._serialized_start=141
  _globals['_PREDICTION']._serialized_end=187
  _globals['_FACERECOGNITION']._serialized_start=189
  _globals['_FACERECOGNITION']._serialized_end=282
# @@protoc_insertion_point(module_scope)
