# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: skin_analysis.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'skin_analysis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13skin_analysis.proto\x12\x06vision\"U\n\x0e\x41nalyzeRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x11\n\x04\x63onf\x18\x02 \x01(\x02H\x00\x88\x01\x01\x12\x10\n\x03iou\x18\x03 \x01(\x02H\x01\x88\x01\x01\x42\x07\n\x05_confB\x06\n\x04_iou\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"K\n\x0b\x42oundingBox\x12\x1d\n\x06\x63\x65nter\x18\x01 \x01(\x0b\x32\r.vision.Point\x12\r\n\x05width\x18\x02 \x01(\x02\x12\x0e\n\x06height\x18\x03 \x01(\x02\"p\n\tDetection\x12)\n\x0c\x62ounding_box\x18\x01 \x01(\x0b\x32\x13.vision.BoundingBox\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x10\n\x08\x63lass_id\x18\x03 \x01(\x05\x12\x12\n\nclass_name\x18\x04 \x01(\t\"G\n\x0f\x41nalyzeResponse\x12%\n\ndetections\x18\x01 \x03(\x0b\x32\x11.vision.Detection\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x32J\n\x0cSkinAnalysis\x12:\n\x07\x41nalyze\x12\x16.vision.AnalyzeRequest\x1a\x17.vision.AnalyzeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'skin_analysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZEREQUEST']._serialized_start=31
  _globals['_ANALYZEREQUEST']._serialized_end=116
  _globals['_POINT']._serialized_start=118
  _globals['_POINT']._serialized_end=147
  _globals['_BOUNDINGBOX']._serialized_start=149
  _globals['_BOUNDINGBOX']._serialized_end=224
  _globals['_DETECTION']._serialized_start=226
  _globals['_DETECTION']._serialized_end=338
  _globals['_ANALYZERESPONSE']._serialized_start=340
  _globals['_ANALYZERESPONSE']._serialized_end=411
  _globals['_SKINANALYSIS']._serialized_start=413
  _globals['_SKINANALYSIS']._serialized_end=487
# @@protoc_insertion_point(module_scope)
